# Generated by Django 5.2.4 on 2026-03-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
