# Generated by Django 5.2.4 on 2026-03-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monportfolio', '0002_profile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
