# Generated by Django 5.2.4 on 2026-03-09 13:06

import django.db.models.deletion
import monportfolio.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monportfolio', '0005_profilerole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='events/covers/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/media/images/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='events/media/videos/', validators=[monportfolio.validators.validate_video_upload]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=models.FileField(upload_to='cv/', validators=[monportfolio.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(upload_to='profile/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[monportfolio.validators.validate_image_upload]),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=120)),
                ('os', models.CharField(blank=True, max_length=120)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(blank=True, max_length=120)),
                ('time_spent_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='monportfoli_timesta_179132_idx'), models.Index(fields=['ip_address'], name='monportfoli_ip_addr_94692c_idx'), models.Index(fields=['path'], name='monportfoli_path_33aa73_idx'), models.Index(fields=['session_id'], name='monportfoli_session_c0e42e_idx')],
            },
        ),
    ]
